include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    use_build_context_synchronously: ignore
    deprecated_member_use: ignore

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
